############################
## CHANGE THESE
############################

baseURL: 'https://blog.milindhvijay.com/'
title: Milindh Vijay

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


