############################
## Author
############################

author:
  name: Milindh Vijay Shajiv Nair
  image: author.png
  greeting: "Software Developer and a Network Enthusiast"
  #icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/milindhvijay/
  #- link: https://github.com/milindhvijay/milindhvijay-blog#readme
  - website: https://milindhvijay.com/
  - x-twitter: https://twitter.com/milindhvijay
  # - mastodon: 
  - linkedin: https://www.linkedin.com/in/milindhvijay/
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: mailto:milindhvijay@gmail.com
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

#title: milindhvijay-blog
#description: "Site build with Qubt & Hugo"
#images:
#  - thumbnail.png
